CREATE OR REPLACE DATABASE IMDB;

CREATE FILE FORMAT location_csv
	COMPRESSION = 'AUTO'
	FIELD_DELIMITER = ','
	RECORD_DELIMITER = '\n'
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
	TRIM_SPACE = FALSE
	ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
	ESCAPE = 'NONE'
	ESCAPE_UNENCLOSED_FIELD = '\134'
	DATE_FORMAT = 'AUTO'
	TIMESTAMP_FORMAT = 'AUTO'
	NULL_IF = ('\\N');
CREATE STAGE stage_data
	FILE_FORMAT = location_csv;
CREATE STAGE stage_models;

CREATE TABLE TRAIN_DATASET (REVIEW STRING, SENTIMENT STRING);
PUT file://.\data\TRAIN_DATASET.csv @stage_data
	overwrite=true auto_compress=false;
COPY INTO TRAIN_DATASET
	FROM @stage_data/TRAIN_DATASET.csv;

CREATE TABLE TEST_DATASET (REVIEW STRING, SENTIMENT STRING);
PUT file://.\data\TEST_DATASET.csv @stage_data
	overwrite=true auto_compress=false;
COPY INTO TEST_DATASET
	FROM @stage_data/TEST_DATASET.csv;